name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Formatting check
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --verbose
